// <auto-generated />
using System;
using GestaoAssociadosApp.Infrastructure.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GestaoAssociadosApp.Infrastructure.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AssociadoBeneficiario", b =>
                {
                    b.Property<Guid>("AssociadosId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BeneficiariosId")
                        .HasColumnType("uuid");

                    b.HasKey("AssociadosId", "BeneficiariosId");

                    b.HasIndex("BeneficiariosId");

                    b.ToTable("ASSOCIADO_BENEFICIARIO", (string)null);
                });

            modelBuilder.Entity("AssociadoCargoLideranca", b =>
                {
                    b.Property<Guid>("AssociadosId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CargosLiderancaId")
                        .HasColumnType("uuid");

                    b.HasKey("AssociadosId", "CargosLiderancaId");

                    b.HasIndex("CargosLiderancaId");

                    b.ToTable("ASSOCIADO_CARGOLIDERANCA", (string)null);
                });

            modelBuilder.Entity("AssociadoEmpresa", b =>
                {
                    b.Property<Guid>("AssociadosId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EmpresasId")
                        .HasColumnType("uuid");

                    b.HasKey("AssociadosId", "EmpresasId");

                    b.HasIndex("EmpresasId");

                    b.ToTable("ASSOCIADO_EMPRESA", (string)null);
                });

            modelBuilder.Entity("AssociadoEndereco", b =>
                {
                    b.Property<Guid>("AssociadosId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EnderecosId")
                        .HasColumnType("uuid");

                    b.HasKey("AssociadosId", "EnderecosId");

                    b.HasIndex("EnderecosId");

                    b.ToTable("ASSOCIADO_ENDERECO", (string)null);
                });

            modelBuilder.Entity("AssociadoGrupamento", b =>
                {
                    b.Property<Guid>("AssociadosId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GrupamentosId")
                        .HasColumnType("uuid");

                    b.HasKey("AssociadosId", "GrupamentosId");

                    b.HasIndex("GrupamentosId");

                    b.ToTable("ASSOCIADO_GRUPAMENTO", (string)null);
                });

            modelBuilder.Entity("EmpresaEndereco", b =>
                {
                    b.Property<Guid>("EmpresasId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EnderecosId")
                        .HasColumnType("uuid");

                    b.HasKey("EmpresasId", "EnderecosId");

                    b.HasIndex("EnderecosId");

                    b.ToTable("EMPRESA_ENDERECO", (string)null);
                });

            modelBuilder.Entity("GestaoAssociadosApp.Domain.Entities.AreaAtuacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ID");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ATIVO");

                    b.Property<DateTime>("DataAlteracao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DATAALTERACAO")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("DataInclusao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DATAINCLUSAO")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("NOME");

                    b.Property<Guid>("SetorMercadoId")
                        .HasColumnType("uuid")
                        .HasColumnName("SETORMERCADO_ID");

                    b.HasKey("Id");

                    b.HasIndex("SetorMercadoId");

                    b.ToTable("AREAATUACAO", (string)null);
                });

            modelBuilder.Entity("GestaoAssociadosApp.Domain.Entities.Associado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ID");

                    b.Property<Guid>("AreaAtuacaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("AREAATUACAO_ID");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ATIVO");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("CPF");

                    b.Property<string>("ConexoesEstrategicas")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("CONEXOESESTRATEGICAS   ");

                    b.Property<Guid>("ContatoEmergenciaId")
                        .HasColumnType("uuid")
                        .HasColumnName("CONTATOEMERGENCIA_ID");

                    b.Property<DateTime>("DataAlteracao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DATAALTERACAO")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("DataInclusao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DATAINCLUSAO")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("DataIngresso")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DATAINGRESSO");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DATANASCIMENTO");

                    b.Property<DateTime?>("DataPagtoPrimeiraAnuidade")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DATAPAGTOPRIMEIRAANUIDADE");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DATAVENCIMENTO");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("EMAIL");

                    b.Property<int>("EstadoCivil")
                        .HasMaxLength(15)
                        .HasColumnType("integer")
                        .HasColumnName("ESTADOCIVIL");

                    b.Property<byte[]>("Foto")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("FOTO");

                    b.Property<string>("InteressesPessoais")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("INTERESSESPESSOAIS");

                    b.Property<string>("Nacionalidade")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("NACIONALIDADE");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("NOME");

                    b.Property<string>("NomeProfissional")
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("NOMEPROFISSIONAL");

                    b.Property<Guid>("PadrinhoId")
                        .HasColumnType("uuid")
                        .HasColumnName("PADRINHO_ID");

                    b.Property<string>("PrincipaisProblemas")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("PRINCIPAISPROBLEMAS");

                    b.Property<string>("Profissao")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("PROFISSAO");

                    b.Property<string>("PublicoIdeal")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("PUBLICOIDEAL");

                    b.Property<string>("RGNumero")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("RGNUMERO");

                    b.Property<string>("RGOrgaoEmissor")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("RGORGAOEMISSOR");

                    b.Property<string>("RGUF")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("RGUF");

                    b.Property<string>("RedeSocialInstagram")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("REDESOCIALINSTAGRAM");

                    b.Property<string>("RedeSocialLinkedIn")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("REDESOCIALLINKEDIN");

                    b.Property<string>("RedeSocialOutros")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("REDESOCIALOUTROS");

                    b.Property<string>("RedeSocialYouTube")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("REDESOCIALYOUTUBE");

                    b.Property<Guid>("SetorMercadoId")
                        .HasColumnType("uuid")
                        .HasColumnName("SETORMERCADO_ID");

                    b.Property<string>("Site")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("SITE");

                    b.Property<int>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("integer")
                        .HasColumnName("STATUS");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("TELEFONE");

                    b.HasKey("Id");

                    b.HasIndex("AreaAtuacaoId");

                    b.HasIndex("CPF")
                        .IsUnique();

                    b.HasIndex("ContatoEmergenciaId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PadrinhoId");

                    b.HasIndex("SetorMercadoId");

                    b.ToTable("ASSOCIADO", (string)null);
                });

            modelBuilder.Entity("GestaoAssociadosApp.Domain.Entities.AssociadoEquipe", b =>
                {
                    b.Property<Guid>("AssociadoId")
                        .HasColumnType("uuid")
                        .HasColumnName("ASSOCIADO_ID");

                    b.Property<Guid>("EquipeId")
                        .HasColumnType("uuid")
                        .HasColumnName("EQUIPE_ID");

                    b.Property<int>("OrigemAssociado")
                        .HasMaxLength(15)
                        .HasColumnType("integer")
                        .HasColumnName("ORIGEMASSOCIADO");

                    b.HasKey("AssociadoId", "EquipeId");

                    b.HasIndex("EquipeId");

                    b.ToTable("ASSOCIADO_EQUIPE", (string)null);
                });

            modelBuilder.Entity("GestaoAssociadosApp.Domain.Entities.Beneficiario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ID");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ATIVO");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("CPF");

                    b.Property<DateTime>("DataAlteracao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DATAALTERACAO")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("DataInclusao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DATAINCLUSAO")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DATANASCIMENTO");

                    b.Property<string>("GrauParentesco")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("GRAUPARENTESCO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("NOME");

                    b.Property<decimal>("Percentual")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("PERCENTUAL");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("TELEFONE");

                    b.HasKey("Id");

                    b.HasIndex("CPF")
                        .IsUnique();

                    b.ToTable("BENEFICIARIO", (string)null);
                });

            modelBuilder.Entity("GestaoAssociadosApp.Domain.Entities.CargoLideranca", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ID");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ATIVO");

                    b.Property<string>("Classificacao")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("CLASSIFICACAO");

                    b.Property<DateTime>("DataAlteracao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DATAALTERACAO")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DATAFIM");

                    b.Property<DateTime>("DataInclusao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DATAINCLUSAO")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DataInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DATAINICIO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("NOME");

                    b.Property<int?>("Status")
                        .HasMaxLength(10)
                        .HasColumnType("integer")
                        .HasColumnName("STATUS");

                    b.HasKey("Id");

                    b.ToTable("CARGOLIDERANCA", (string)null);
                });

            modelBuilder.Entity("GestaoAssociadosApp.Domain.Entities.ContatoEmergencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ID");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ATIVO");

                    b.Property<DateTime>("DataAlteracao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DATAALTERACAO")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("DataInclusao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DATAINCLUSAO")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("GrauRelacionamento")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("GRAURELACIONAMENTO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("NOME");

                    b.Property<string>("TelefonePrincipal")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("TELEFONEPRINCIPAL");

                    b.Property<string>("TelefoneSecundario")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("TELEFONESECUNDARIO");

                    b.HasKey("Id");

                    b.ToTable("CONTATOEMERGENCIA", (string)null);
                });

            modelBuilder.Entity("GestaoAssociadosApp.Domain.Entities.Empresa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ID");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ATIVO");

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("CNPJ");

                    b.Property<DateTime>("DataAlteracao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DATAALTERACAO")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("DataInclusao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DATAINCLUSAO")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<byte[]>("Logomarca")
                        .HasColumnType("bytea")
                        .HasColumnName("LOGOMARCA");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("RAZAOSOCIAL");

                    b.HasKey("Id");

                    b.HasIndex("CNPJ")
                        .IsUnique();

                    b.ToTable("EMPRESA", (string)null);
                });

            modelBuilder.Entity("GestaoAssociadosApp.Domain.Entities.Endereco", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ID");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ATIVO");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("BAIRRO");

                    b.Property<string>("CEP")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("CEP");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("CIDADE");

                    b.Property<string>("Complemento")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("COMPLEMENTO");

                    b.Property<DateTime>("DataAlteracao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DATAALTERACAO")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("DataInclusao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DATAINCLUSAO")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("ESTADO");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("NUMERO");

                    b.Property<string>("Rua")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("RUA");

                    b.HasKey("Id");

                    b.ToTable("ENDERECO", (string)null);
                });

            modelBuilder.Entity("GestaoAssociadosApp.Domain.Entities.Equipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ID");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ATIVO");

                    b.Property<DateTime>("DataAlteracao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DATAALTERACAO")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("DataEfetivaLancamento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DATAEFETIVALANCAMENTO");

                    b.Property<DateTime>("DataInclusao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DATAINCLUSAO")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("DataInicioFormacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DATAINICIOFORMACAO");

                    b.Property<DateTime>("DataPrevisaoLancamento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DATAPREVISAOLANCAMENTO");

                    b.Property<string>("DiaReuniao")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("DIAREUNIAO");

                    b.Property<string>("HoraReuniao")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("HORAREUNIAO");

                    b.Property<string>("LinkReuniao")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("LINKREUNIAO");

                    b.Property<string>("LocalReuniao")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("LOCALREUNIAO");

                    b.Property<string>("ModeloReuniao")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("MODELOREUNIAO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("NOME");

                    b.HasKey("Id");

                    b.ToTable("EQUIPE", (string)null);
                });

            modelBuilder.Entity("GestaoAssociadosApp.Domain.Entities.Grupamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ID");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ATIVO");

                    b.Property<DateTime>("DataAlteracao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DATAALTERACAO")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("DataInclusao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DATAINCLUSAO")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("NOME");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("SIGLA");

                    b.HasKey("Id");

                    b.ToTable("GRUPAMENTO", (string)null);
                });

            modelBuilder.Entity("GestaoAssociadosApp.Domain.Entities.SetorMercado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ID");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ATIVO");

                    b.Property<DateTime>("DataAlteracao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DATAALTERACAO")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("DataInclusao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DATAINCLUSAO")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("NOME");

                    b.HasKey("Id");

                    b.ToTable("SETORMERCADO", (string)null);
                });

            modelBuilder.Entity("AssociadoBeneficiario", b =>
                {
                    b.HasOne("GestaoAssociadosApp.Domain.Entities.Associado", null)
                        .WithMany()
                        .HasForeignKey("AssociadosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestaoAssociadosApp.Domain.Entities.Beneficiario", null)
                        .WithMany()
                        .HasForeignKey("BeneficiariosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AssociadoCargoLideranca", b =>
                {
                    b.HasOne("GestaoAssociadosApp.Domain.Entities.Associado", null)
                        .WithMany()
                        .HasForeignKey("AssociadosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestaoAssociadosApp.Domain.Entities.CargoLideranca", null)
                        .WithMany()
                        .HasForeignKey("CargosLiderancaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AssociadoEmpresa", b =>
                {
                    b.HasOne("GestaoAssociadosApp.Domain.Entities.Associado", null)
                        .WithMany()
                        .HasForeignKey("AssociadosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestaoAssociadosApp.Domain.Entities.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AssociadoEndereco", b =>
                {
                    b.HasOne("GestaoAssociadosApp.Domain.Entities.Associado", null)
                        .WithMany()
                        .HasForeignKey("AssociadosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestaoAssociadosApp.Domain.Entities.Endereco", null)
                        .WithMany()
                        .HasForeignKey("EnderecosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AssociadoGrupamento", b =>
                {
                    b.HasOne("GestaoAssociadosApp.Domain.Entities.Associado", null)
                        .WithMany()
                        .HasForeignKey("AssociadosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestaoAssociadosApp.Domain.Entities.Grupamento", null)
                        .WithMany()
                        .HasForeignKey("GrupamentosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EmpresaEndereco", b =>
                {
                    b.HasOne("GestaoAssociadosApp.Domain.Entities.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestaoAssociadosApp.Domain.Entities.Endereco", null)
                        .WithMany()
                        .HasForeignKey("EnderecosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GestaoAssociadosApp.Domain.Entities.AreaAtuacao", b =>
                {
                    b.HasOne("GestaoAssociadosApp.Domain.Entities.SetorMercado", "SetorMercado")
                        .WithMany("AreasAtuacao")
                        .HasForeignKey("SetorMercadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SetorMercado");
                });

            modelBuilder.Entity("GestaoAssociadosApp.Domain.Entities.Associado", b =>
                {
                    b.HasOne("GestaoAssociadosApp.Domain.Entities.AreaAtuacao", "AreaAtuacao")
                        .WithMany("Associados")
                        .HasForeignKey("AreaAtuacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestaoAssociadosApp.Domain.Entities.ContatoEmergencia", "ContatoEmergencia")
                        .WithMany("Associados")
                        .HasForeignKey("ContatoEmergenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestaoAssociadosApp.Domain.Entities.Associado", "Padrinho")
                        .WithMany()
                        .HasForeignKey("PadrinhoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestaoAssociadosApp.Domain.Entities.SetorMercado", "SetorMercado")
                        .WithMany("Associados")
                        .HasForeignKey("SetorMercadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AreaAtuacao");

                    b.Navigation("ContatoEmergencia");

                    b.Navigation("Padrinho");

                    b.Navigation("SetorMercado");
                });

            modelBuilder.Entity("GestaoAssociadosApp.Domain.Entities.AssociadoEquipe", b =>
                {
                    b.HasOne("GestaoAssociadosApp.Domain.Entities.Associado", "Associado")
                        .WithMany("AssociadoEquipes")
                        .HasForeignKey("AssociadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestaoAssociadosApp.Domain.Entities.Equipe", "Equipe")
                        .WithMany("AssociadoEquipes")
                        .HasForeignKey("EquipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Associado");

                    b.Navigation("Equipe");
                });

            modelBuilder.Entity("GestaoAssociadosApp.Domain.Entities.AreaAtuacao", b =>
                {
                    b.Navigation("Associados");
                });

            modelBuilder.Entity("GestaoAssociadosApp.Domain.Entities.Associado", b =>
                {
                    b.Navigation("AssociadoEquipes");
                });

            modelBuilder.Entity("GestaoAssociadosApp.Domain.Entities.ContatoEmergencia", b =>
                {
                    b.Navigation("Associados");
                });

            modelBuilder.Entity("GestaoAssociadosApp.Domain.Entities.Equipe", b =>
                {
                    b.Navigation("AssociadoEquipes");
                });

            modelBuilder.Entity("GestaoAssociadosApp.Domain.Entities.SetorMercado", b =>
                {
                    b.Navigation("AreasAtuacao");

                    b.Navigation("Associados");
                });
#pragma warning restore 612, 618
        }
    }
}
